
export default {
    THEME_CHANGE:'THEME_CHANGE',

    REQUEST_DATA:'REQUEST_DATA',

    REFRESH_DATA_SUCCESS:'REFRESH_DATA_SUCCESS',
    REFRESH_DATA_Fail:'REFRESH_DATA_Fail',

    LOAD_MORE_DATA:'LOAD_MORE_DATA',
    LOAD_MORE_DATA_SUCCESS:'LOAD_MORE_DATA_SUCCESS',
    LOAD_MORE_DATA_Fail:'LOAD_MORE_DATA_Fail',
}
