
export default {
    THEME_CHANGE:'THEME_CHANGE',

    REQUEST_DATA:'REQUEST_DATA',

    REFRESH_DATA_SUCCESS:'REFRESH_DATA_SUCCESS',
    REFRESH_DATA_Fail:'REFRESH_DATA_Fail',

    LOAD_MORE_DATA:'LOAD_MORE_DATA',
    LOAD_MORE_DATA_SUCCESS:'LOAD_MORE_DATA_SUCCESS',
    LOAD_MORE_DATA_Fail:'LOAD_MORE_DATA_Fail',

    TRENDING_REQUEST_DATA:'TRENDING_REQUEST_DATA',
    TRENDING_REFRESH_DATA_SUCCESS:'TRENDING_REFRESH_DATA_SUCCESS',
    TRENDING_REFRESH_DATA_Fail:'TRENDING_REFRESH_DATA_Fail',
    TRENDING_LOAD_MORE_DATA:'TRENDING_LOAD_MORE_DATA',
    TRENDING_LOAD_MORE_DATA_SUCCESS:'TRENDING_LOAD_MORE_DATA_SUCCESS',
    TRENDING_LOAD_MORE_DATA_Fail:'TRENDING_LOAD_MORE_DATA_Fail',

    COLLECTION_LOAD_DATA:'COLLECTION_REQUEST_DATA',
    COLLECTION_LOAD_DATA_SUCCESS:'COLLECTION_LOAD_DATA_SUCCESS',
    COLLECTION_LOAD_DATA_Fail:'COLLECTION_LOAD_DATA_Fail',
}
